### ISSUE TITLE
Is ArrayFire free to redistribution?

### ISSUE THREAD

**Issue by Oceania2018** [arrayfire/arrayfire-dotnet#15]
Hi gentleman, I here to wondering if I can redistribute ArrayFire's libraries along with other open source project? I've raised a discuss issue [here](https://github.com/SciSharp/NumSharp/issues/195). Hope to get your advice.

**Comment by 9prady9** [comment]
@Oceania2018 ArrayFire is licensed under BSD-3 license, please refer to the following link to get more details about redistribution details.

https://opensource.org/licenses/BSD-3-Clause

**Comment by Oceania2018** [comment]
@9prady9 Thank you for quick response. So we can include the binary within my libraries. As just meet the term:
```
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
```
