### ISSUE TITLE
Adopt third part CI tool AppVeyor

### ISSUE THREAD

**Issue by Oceania2018** [arrayfire/arrayfire-dotnet#20]
@9prady9 Do you mind we use the CI tool AppVeyor? If not, I'll setup the CI process on AppVeyor, and place badge on the README.

**Comment by 9prady9** [comment]
@Oceania2018 Can you please join me [here ](https://join.slack.com/t/arrayfire-org/shared_invite/enQtMjI4MjIzMDMzMTczLWM4ODIyZjA3YmY3NWEwMjk2N2Q0YTQyNGMwZmU4ZjkxNGU0MjYzYmUzYTg3ZTM0MDQxOTE2OTJjNGVkOGEwN2M) on slack, we can discuss this much more quickly over there.

**Comment by 9prady9** [comment]
Are you talking about something like I have setup on [forge](https://github.com/arrayfire/forge/blob/master/appveyor.yml) ?

**Comment by Oceania2018** [comment]
correct

**Comment by 9prady9** [comment]
Sure, go ahead.

**Comment by 9prady9** [comment]
@Oceania2018 Can this be considered done ? I see a badge in the new README.

**Comment by Oceania2018** [comment]
Yes, it's done.
