### ISSUE TITLE
dot issue

### ISSUE THREAD

**Issue by Oceania2018** [arrayfire/arrayfire-dotnet#23]
Whe I run the HelloWorld and try to do `dot`;

```csharp
            Device.SetBackend(Backend.DEFAULT);
            Device.PrintInfo();

            var arr1 = Data.RandNormal<float>(3, 3);
            var arr2 = Data.RandNormal<float>(3, 3);
            var arr3 = arr1 + arr2;
            var arr4 = Matrix.Multiply(arr1, arr2);
            var arr5 = Arith.Sin(arr1) + Arith.Cos(arr2);
            var arr6 = Vector.Dot(arr1, arr2);
```

![image](https://user-images.githubusercontent.com/1705364/55289122-b7bfc700-5387-11e9-94c0-f141a09cc921.png)

**Comment by 9prady9** [comment]
Uploading the sample input and output shown by @Oceania2018  on our slack conversation here.

![image](https://user-images.githubusercontent.com/3270458/55307481-5118d700-5475-11e9-99d9-f19f95da3369.png)
![image(1)](https://user-images.githubusercontent.com/3270458/55307483-524a0400-5475-11e9-94b7-9ce07eae056f.png)

The type of batching you want to do dot product can be done using [matmul](http://arrayfire.org/docs/group__blas__func__matmul.htm#ga63306b6ed967bd1055086db862fe885b). The arrayfire function named dot product only handles the case of `dot(vector_array, vector_array)`. Having said that, like I pointed at the beginning of this paragraph, batched dot product can be carried out using matrix multiplication.

**Comment by Oceania2018** [comment]
When I pass `int`, it raises error. If I change to `float` or `double`, it works in `matmul`.

**Comment by 9prady9** [comment]
Matmul is supported for floating point types: float, double and their complex counterparts. Hence, error is returned by C API.

**Comment by Oceania2018** [comment]
the `matmul` return the result is not correct. It should be `[[7, 11], [4, 7]]`

**Comment by 9prady9** [comment]
What is the result of matmul from arrayfire ?

**Comment by Oceania2018** [comment]
`[[9, 8], [5, 5]]`

**Comment by 9prady9** [comment]
The image you uploaded shows np.dot result as `[[9, 8], [5, 5]]`.

In any case, irrespective of inputs using matrix multiplication is a standard way to obtain bunch of dot products quickly.  Please note that ArrayFire expects data to be in column major format, may be that is the reason behind different output.
