### ISSUE TITLE
Publish in NuGet

### ISSUE THREAD

**Issue by sirinath** [arrayfire/arrayfire-dotnet#9]
Can you publish this in NuGet (https://www.nuget.org/)

**Comment by Oceania2018** [comment]
@9prady9  I can help publish if you don't mind.

**Comment by 9prady9** [comment]
@Oceania2018 My only concern is, the wrapper is not full fledged, if we are releasing an incomplete, is there a way to mark it so in nuget packaging ? Like pre-releases or something like that ?

**Comment by Oceania2018** [comment]
Yes, we can flag it as preview or just make version 0.0.1.

**Comment by 9prady9** [comment]
Awesome, please go ahead then.

**Comment by 9prady9** [comment]
We also have to create a tag on github for preview release's corresponding commit.

**Comment by Oceania2018** [comment]
Published. 

![image](https://user-images.githubusercontent.com/1705364/53289439-97cf2f00-375b-11e9-8935-34d2bc86e734.png)

**Comment by 9prady9** [comment]
We should have sample Visual Studio project added to the examples that uses this nuget package.

**Comment by Oceania2018** [comment]
We can install nuget package into the `HelloWorld` project not reference the original ArrayFire project. Am I right?

**Comment by 9prady9** [comment]
@Oceania2018 No idea dude, I have no idea how nuget packages work or if they can be conditionally used in a project. If that isn't possible, perhaps add a copy of helloworld that is titled `nuget_example` that uses nuget ArrayFire instead of locally built version ?

**Comment by 9prady9** [comment]
Irrespective of that, we can close this issue since you have published it to nuget now.
